apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/SayedAtwh/DevOps-End-to-End-AWS-GitOps-Platform.git"
    targetRevision: main
    path: Prometheus
    directory:
      recurse: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
