apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret-java-app
  namespace: monitoring
type: Opaque
stringData:
  webhook: 'https://hooks.slack.com/services/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'