apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-java-app
  namespace: java-app
spec:
  replicas: 3

  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: sayedatwhdevops/java-app:v5
          ports:
            - containerPort: 8090

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          volumeMounts:
            - name: volume-java-app
              mountPath: /app/data

      volumes:
        - name: volume-java-app
          persistentVolumeClaim:
            claimName: pvc-java-app


      