apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-java-app
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  directoryPerms: "700"
  fileSystemId: fs-077454944c535574d